name: Continuous Updates

on:
  push:
    branches: [ dependabot/** ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 20
        persist-credentials: false
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Autofix lockfile
      run: |
        git checkout ${{ github.sha }}^ -- yarn.lock
        yarn
      env:
        YARN_CHECKSUM_BEHAVIOR: update
        YARN_ENABLE_SCRIPTS: 0
    - name: Config Git
      run: |
        git config --global user.name '${{ github.event.commits[0].author.name }}'
        git config --global user.email '${{ github.event.commits[0].author.email }}'
    - name: Commit changes
      run: |
        git add yarn.lock
        git commit --amend --no-edit -n
    - name: Get branch
      uses: rlespinasse/github-slug-action@2.0.0
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ env.GITHUB_REF_SLUG }}
        force: true
